export const ACTION_TYPE = {
    ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
    UPDATE_COUNT: 'UPDATE_COUNT',
    TOGGLE_ORDER: 'TOGGLE_ORDER',
    TOGGLE_ALL_ORDER: 'TOGGLE_ALL_ORDER',
    DELETE_ORDER: 'DELETE_ORDER',
    FILTER_PRODUCTS: 'FILTER_PRODUCTS',
    ON_SUBBMIT_ORDERS: 'ON_SUBBMIT_ORDERS',
};